### ISSUE TITLE
Update Examples for ORAS Artifact Manifests

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#178]
Extending #60, we need examples for ORAS Artifact manifests.

- [x] Upload  ORAS Artifact manifest #172
- [x] Download ORAS Artifact manifest #173
- [x] Download blob of ORAS Artifact manifest #234 
- [x] Copy ORAS Artifact manifest #241
- [x] Copy artifact and its referrers (i.e.  ORAS Artifact manifests) #248

**Comment by wangxiaoxuan273** [comment]
ack

**Comment by wangxiaoxuan273** [comment]
Upload ORAS Artifact manifest: pr #172

**Comment by wangxiaoxuan273** [comment]
Download ORAS Artifact manifest: pr #173

**Comment by wangxiaoxuan273** [comment]
Download blob of ORAS Artifact manifest: pr #234

**Comment by wangxiaoxuan273** [comment]
Copy ORAS Artifact manifest #241

**Comment by wangxiaoxuan273** [comment]
Copy artifact and its referrers (i.e. ORAS Artifact manifests) #248

**Comment by Wwwsylvia** [comment]
Closing as all sub-tasks are done.
